config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :accounts
  resources :services
  resources :document_types
  resources :manage_users
  resources :transactions
  resources :enterprise_aux do
    scope module: :enterprise_aux do
      resources :documents
    end
  end

  resources :vehicles do
    scope module: :vehicles do
      resources :documents
    end
  end

  resources :technicals do
    scope module: :technicals do
      resources :documents
      resources :bonding_dates
    end
  end

  resources :clients do
    scope module: :clients do
      resources :documents
      resources :list_prices
    end
  end

  get '/transactions/close/:id', to: 'transactions#close', as: 'transaction_close'
  get '/transactions/open/:id', to: 'transactions#open', as: 'transaction_open'
  get '/transactions/deliver/:id', to: 'transactions#deliver', as: 'transaction_deliver'
  get '/transactions/check_in/:id', to: 'transactions#check_in', as: 'transaction_check_in'

  namespace :transactions do
    resources :clients, only: :new
    resources :vehicles, only: :new
    resources :technicals, only: :new
    resources :accounts, only: :new
  end

  devise_for :users
  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end
  root to: redirect('/users/sign_in')
  resources :dashboard, only: :index

  namespace :api do
    namespace :v1 do
      get 'calulate_distance', to: 'calculate_distance#distance'
    end
  end

  get 'reports/technical_payment', as: 'technical_payment'
  get 'reports/technical_clearance', as: 'technical_clearance'
  get 'reports/payment_per_vehicle', as: 'payment_per_vehicle'
  get 'reports/vehicle_liquidation', as: 'vehicle_liquidation'
  get 'reports/transaction_report', as: 'transaction_report'
  get 'reports/service_report', as: 'service_report'

end

app/models/service.rb
class Service < ApplicationRecord
  acts_as_paranoid
  belongs_to :enterprise
  has_one :list_price
  has_many :transactions
  validates :name, presence: true
  validates :name, uniqueness: {scope: :enterprise_id, case_sensitive: false }
  before_save :to_upper
end

app/controllers/services_controller.rb
class ServicesController < EnterprisesController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @q = @enterprise.services.ransack(params[:q])
    @pagy, @services = pagy( @q.result)
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = @enterprise.services.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = @enterprise.services.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to edit_service_path(@service), notice: 'El servicio ha sido creado satisfactoriamente.' }
        format.json { render :edit, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to edit_service_path(@service), notice: 'El servicio ha sido actualizado satisfactoriamente.' }
        format.json { render :edit, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'El servicio ha sido destruido satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = @enterprise.services.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def service_params
      params.require(:service).permit(:name, :enterprise_id)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.slim
= form_with(model: service, local: true) do |form|
  = alert_error(service)

  .field
    = form.label :name, "Nombre"
    = form.text_field :name, class: 'form-control'

  .actions
    = form.submit 'Actualizar', class: 'btn btn-primary'
    | |
    = link_to 'Atrás', services_path, class: 'btn btn-warning'

app/views/services/edit.html.slim
- content_for :breadcrumb do
  = render 'components/breadcrumb',
          title: 'Servicios',
          links: [ ['Servicios', services_path],
                   [@service.name, '']]

= render 'form', service: @service

app/views/services/index.html.slim
- content_for :breadcrumb do
  = render 'components/breadcrumb',
          title: 'Servicios',
          links: [ ['Usuarios', '']]

= render "components/search", field_search: :name_cont, url: services_path
table.table
  thead
    tr
      th Nombre
      th colspan="2"

  tbody
    - @services.each do |service|
      tr
        td = service.name
        td = link_to 'Editar', edit_service_path(service),  class: 'btn btn-primary'
        td = link_to 'Destruir', service,
                                method: :delete,
                                data: { confirm: 'Está seguro' },
                                class: 'btn btn-danger'
= pagy_bootstrap_nav(@pagy).html_safe
= pagy_bootstrap_nav_js(@pagy).html_safe

br

= link_to 'Nuevo Servicio', new_service_path,  class: 'btn btn-primary'

app/views/services/new.html.slim
- content_for :breadcrumb do
  = render 'components/breadcrumb',
          title: 'Servicios',
          links: [ ['Servicios', services_path],
                  ['Nuevo', '']]

= render 'form', service: @service

app/views/services/show.html.slim
p
  strong Nombre:
  = @service.name

= link_to 'Editar', edit_service_path(@service), class: 'btn btn-primary'
| |
= link_to 'Atrás', services_path,  class: 'btn btn-warning'