config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :accounts
  resources :services
  resources :document_types
  resources :manage_users
  resources :transactions
  resources :enterprise_aux do
    scope module: :enterprise_aux do
      resources :documents
    end
  end

  resources :vehicles do
    scope module: :vehicles do
      resources :documents
    end
  end

  resources :technicals do
    scope module: :technicals do
      resources :documents
      resources :bonding_dates
    end
  end

  resources :clients do
    scope module: :clients do
      resources :documents
      resources :list_prices
    end
  end

  get '/transactions/close/:id', to: 'transactions#close', as: 'transaction_close'
  get '/transactions/open/:id', to: 'transactions#open', as: 'transaction_open'
  get '/transactions/deliver/:id', to: 'transactions#deliver', as: 'transaction_deliver'
  get '/transactions/check_in/:id', to: 'transactions#check_in', as: 'transaction_check_in'

  namespace :transactions do
    resources :clients, only: :new
    resources :vehicles, only: :new
    resources :technicals, only: :new
    resources :accounts, only: :new
  end

  devise_for :users
  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end
  root to: redirect('/users/sign_in')
  resources :dashboard, only: :index

  namespace :api do
    namespace :v1 do
      get 'calulate_distance', to: 'calculate_distance#distance'
    end
  end

  get 'reports/technical_payment', as: 'technical_payment'
  get 'reports/technical_clearance', as: 'technical_clearance'
  get 'reports/payment_per_vehicle', as: 'payment_per_vehicle'
  get 'reports/vehicle_liquidation', as: 'vehicle_liquidation'
  get 'reports/transaction_report', as: 'transaction_report'
  get 'reports/service_report', as: 'service_report'

end

app/models/client.rb
class Client < ApplicationRecord
  acts_as_paranoid
  belongs_to :enterprise
  has_many :transactions
  has_many :documents, as: :documentable
  has_many :list_prices
  has_and_belongs_to_many :accounts

  validates :nombre, presence: true
  validates :identificacion, presence: true
  validates :identificacion, uniqueness: {scope: :enterprise_id, case_sensitive: false }
  validates :telefono, presence: true

  enum regimen: { 'COMUN': 'COMUN', SIMPLIFICADO: 'SIMPLIFICADO' }
  enum tipo_identificacion: {'CEDULA DE CIUDADANIA': 'CC', 'CEDULA DE EXTRANJERÍA':'CE', PASAPORTE:'P', 'REGISTRO CIVIL':'RC', NIT:'NIT'}
  before_save :to_upper

  def arrays_acounts
    @array = []
    self.accounts.each do |ac|
      @array.push([ac.id, ac.name])
    end
    @array
  end

  def identification_name
    "#{self.identificacion} #{self.nombre}"
  end

  private def to_upper
    self.direccion.try(:upcase!)
    self.actividad_comercial.try(:upcase!)
    self.nombre.try(:upcase!)
    self.ciudad.try(:upcase!)
  end

end

app/controllers/clients/base_controller.rb
module Clients
  class BaseController < EnterprisesController
    before_action :load_client

    private

    def load_client
      @client = @enterprise.clients.find(client_id)
    end

    def client_id
      params.require(:client_id)
    end
  end
end

app/controllers/clients/documents_controller.rb
module Clients
  class DocumentsController < BaseController
    before_action :set_document, only: [:show, :edit, :update, :destroy]

    def index
      @q = @client.documents.ransack(params[:q])
      @pagy, @documents = pagy(@q.result.includes(:document_type))
    end

    def new
      @document = @client.documents.new
      @document.pictures.build
    end

    def create
      @document = @client.documents.new(document_params)
      if @document.save
        redirect_to edit_client_document_path(@client, @document), notice: 'Document was successfully created.'
      else
        render :new
      end
    end

    def edit
      @document.pictures.build
    end

    def update
      if @document.update(document_params)
        redirect_to edit_client_document_path(@client, @document), notice: 'Document was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @document.destroy
      redirect_to client_documents_path, notice: 'Document was deleted'
    end

    def show
      respond_to do |format|
        format.html
        format.pdf do
          render pdf: "Documentos #{@client.nombre}",
                 title: "PDF Documentos #{@client.nombre}",
                 layout: 'pdf'
        end
      end
    end

    private

    def set_document
      @document = @client.documents.find(params[:id])
    end

    def document_params
      params.require(:document).permit(:document_type_id, :renewable, :due_date,
                                       pictures_attributes: [ :id, :image, :image_cache, :_destroy, attachments:[]]
      )
    end
  end
end

app/controllers/clients/list_prices_controller.rb
module Clients
  class ListPricesController < BaseController
    before_action :set_list_price, only: [:show, :edit, :update, :destroy]

    def index
      @q = @client.list_prices.ransack(params[:q])
      @pagy, @list_prices = pagy( @q.result.includes(:service) )
    end

    def new
      @list_price = @client.list_prices.new
    end

    def create
      @list_price = @client.list_prices.new(list_price_params)
      if @list_price.save
        redirect_to edit_client_list_price_path(@client, @list_price),  notice: 'List price was successfully created.'
      else
        render :new
      end
    end

    def update
      if @list_price.update(list_price_params)
        redirect_to edit_client_list_price_path(@client, @list_price),  notice: 'List price was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @list_price.destroy
      redirect_to client_list_prices_path, notice: 'List_price was deleted'
    end

    private

    def set_list_price
      @list_price = @client.list_prices.find(params[:id])
    end

    def list_price_params
      params.require(:list_price).permit(:service_id, :flag, :waiting_hours_value, :kilometer_value,
                                         :night_surcharge, :red_zone_value, :holiday_surcharge)
    end
  end
end

app/controllers/clients_controller.rb
class ClientsController < EnterprisesController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @q = @enterprise.clients.ransack(params[:q])
    @pagy, @clients = pagy( @q.result, items: params[:per_page] == 'all' ? @q.result.count : 10 )
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    respond_to do |format|
      format.html
      format.json
      format.pdf do
        render pdf: "technical",
               template: "clients/show.html.slim",
               title: 'PDF  Cliente',
               layout: 'pdf'
      end
    end
  end

  # GET /clients/new
  def new
    @client = @enterprise.clients.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = @enterprise.clients.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to edit_client_path(@client), notice: 'El cliente ha sido creado satisfactoriamente.' }
        format.js
        format.json { render json: @client, status: :created }
      else
        format.html { render :new }
        format.js
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to  edit_client_path(@client), notice: 'El cliente ha sido actualizado satisfactoriamente.' }
        format.json { render :edit, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'El cliente ha sido destruido satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = @enterprise.clients.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:nombre, :tipo_identificacion, :identificacion, :razon_social, :regimen, :actividad_comercial,
                                     :direccion, :ciudad, :telefono, :email, account_ids: [])
    end
end

app/controllers/transactions/clients_controller.rb
class Transactions::ClientsController < EnterprisesController
  def new
    @transaction = @enterprise.transactions.new(client_attributes: {})
  end
end

app/helpers/clients/document_helper.rb
module Clients::DocumentHelper
  def expired_date(document)
    if document.due_date.to_s.blank?
      expired=6
    else
      expired = ((Date.parse document.due_date.to_s) - (Date.parse Time.now.to_s)).to_i
    end

    if expired <= 0 && !document.renewable
      @expired = "<div class='alert alert-danger' role='alert'>
                    Tiene Documentos vencidos!
                  </div>"
    else
      @expired= ''
    end
  end

  def expired
    @expired
  end

end

app/helpers/clients/list_price_helper.rb
module Clients::ListPriceHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/transactions/clients_helper.rb
module Transactions::ClientsHelper
end

app/views/clients/_form.html.slim
= form_with(model: client, local: true) do |form|
  = alert_error(client)

  - unless @client.id.nil?
    = render 'clients/tabs', page: 'general'

  = render 'clients/form_fields', f: form

  .actions
    = form.submit 'Actualizar', class: 'btn btn-primary'
    | |
    = link_to 'Atras', clients_path, class: 'btn btn-warning'

app/views/clients/_form_fields.html.slim
= f.label "Nombre"
= f.text_field :nombre, class: 'form-control', id:'campo'

= f.label :account_ids, "Cuentas"
br
= f.collection_select :account_ids, @enterprise.accounts, :id, :name,
                        { },
                        { multiple: true, class: 'multiple-select' , id:'campo'}
br
= f.label :tipo_identificacion,"Tipo de Identificación"
= f.select :tipo_identificacion, Client.tipo_identificacions.keys, {include_blank:true}, class: 'form-control', id:'campo'

= f.label "Identificación"
= f.text_field :identificacion, class: 'form-control', id:'campo'


= f.label "Razón social"
= f.text_field :razon_social, class: 'form-control', id:'campo'


= f.label "Regimen"
= f.select :regimen, Client.regimen.keys, {}, class: 'form-control', id:'campo'


= f.label "Actividad comercial"
= f.text_field :actividad_comercial, class: 'form-control', id:'campo'


= f.label "Direccion"
= f.text_field :direccion, class: 'form-control', id:'campo'


= f.label "Ciudad"
= f.text_field :ciudad, class: 'form-control', id:'campo'


= f.label "Teléfono"
= f.telephone_field :telefono, class: 'form-control', id:'campo'


= f.label "Email"
= f.email_field :email, class: 'form-control', id:'campo'

app/views/clients/_tabs.html.slim
nav
  .nav.nav-tabs#nav-tab role="tablist"
    a class="nav-item nav-link #{page=='general' ? 'active': ''}" href="#{edit_client_path(@client)}" role="tab" aria-controls="nav-General" aria-selected="true"
      | General
    a class="nav-item nav-link #{page=='tprecios' ? 'active': ''}" href="#{client_list_prices_path(@client)}" role="tab" aria-controls="nav-Tabla_precios" aria-selected="true" Tabla de Precios
    a class="nav-item nav-link #{page=='document' ? 'active': ''}" role="tab" aria-controls="nav-documentos" aria-selected="true" href = "#{client_documents_path(@client)}"
      | Documentos

app/views/clients/create.js.erb
$(".alert").alert('close');
if(<%= @client.valid? %> == true){
  $.get('/clients.json?per_page=all', function(data){ 
    $("#clientes").empty();
    $('#clientes').append($('<option>'));

    $.each(data, function (i, val) {
      $('#clientes').append($('<option>',{
        value: val.id,
        text: val.nombre,
        selected: val.id == parseInt("<%= @client.id %>")
      }));
    });
      $('[id=campo]').each(function () {
          $(this).val('');
      });
    $('#new_client_modal').modal('toggle');
  });
} else {
  <% @client.errors.each do |i, v| %>
    $(".modal-body").prepend("<div class='alert alert-danger' role='alert'> <%= i  %>  <%= v  %> "+
        "<button type='button' class='close' data-dismiss='alert' aria-label='Close'>" +
        "<span aria-hidden='true'>&times;</span>" +"</button>"+ "</div>");
    console.log("<%= i %>")
    console.log("<%= v %>")
  <% end %>
}

app/views/clients/edit.html.slim
- content_for :breadcrumb do
  = render 'components/breadcrumb',
              title: 'Clientes',
              links: [['Clientes', clients_path], [@client.nombre, ''] ]

= link_to 'Crear PDF', client_path(@client, :format => :pdf), class: 'btn btn-primary'

= render 'form', client: @client

app/views/clients/index.html.slim
- content_for :breadcrumb do
  = render 'components/breadcrumb',
              title: 'Clientes',
              links: [ ['Clientes', ''] ]

= render "components/search",
          url: clients_path,
          field_search: :nombre_or_identificacion_or_razon_social_or_regimen_or_actividad_comercial_or_direccion_or_ciudad_or_telefono_or_email_cont

table.table
  thead
    tr
      th Nombre
      th Identificación
      th Razon social
      th Reginmen
      th Actividad comercial
      th Dirección
      th Ciudad
      th Teléfono
      th Email
      th colspan="2"

  tbody
  -@clients.each do |client|
    tr
      td = client.nombre
      td = client.identificacion
      td = client.razon_social
      td = client.regimen
      td = client.actividad_comercial
      td = client.direccion
      td = client.ciudad
      td = client.telefono
      td = client.email
      td = link_to 'Editar', edit_client_path(client), class: 'btn btn-primary'
      td = link_to 'Destruir', client, method: :delete, data: {confirm: 'Estas Seguro?'}, class: 'btn btn-danger'
= pagy_bootstrap_nav(@pagy).html_safe
= pagy_bootstrap_nav_js(@pagy).html_safe

br

= link_to 'Nuevo Cliente', new_client_path, class: 'btn btn-primary'

app/views/clients/new.html.slim
- content_for :breadcrumb do
  = render 'components/breadcrumb',
              title: 'Clientes',
              links: [['Clientes', clients_path], ['Nuevo', ''] ]

= render 'form', client: @client

app/views/clients/show.html.slim
p
  strong Nombre:
  = @client.nombre

p
  strong Identificación:
  = @client.identificacion

p
  strong Razón social:
  = @client.razon_social

p
  strong Regimen:
  = @client.regimen

p
  strong Actividad comercial:
  = @client.actividad_comercial

p
  strong Dirección:
  = @client.direccion

p
  strong Ciudad:
  = @client.ciudad


p
  strong Teléfono:
  = @client.telefono

p
  strong Email:
  = @client.email