config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :accounts
  resources :services
  resources :document_types
  resources :manage_users
  resources :transactions
  resources :enterprise_aux do
    scope module: :enterprise_aux do
      resources :documents
    end
  end

  resources :vehicles do
    scope module: :vehicles do
      resources :documents
    end
  end

  resources :technicals do
    scope module: :technicals do
      resources :documents
      resources :bonding_dates
    end
  end

  resources :clients do
    scope module: :clients do
      resources :documents
      resources :list_prices
    end
  end

  get '/transactions/close/:id', to: 'transactions#close', as: 'transaction_close'
  get '/transactions/open/:id', to: 'transactions#open', as: 'transaction_open'
  get '/transactions/deliver/:id', to: 'transactions#deliver', as: 'transaction_deliver'
  get '/transactions/check_in/:id', to: 'transactions#check_in', as: 'transaction_check_in'

  namespace :transactions do
    resources :clients, only: :new
    resources :vehicles, only: :new
    resources :technicals, only: :new
    resources :accounts, only: :new
  end

  devise_for :users
  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end
  root to: redirect('/users/sign_in')
  resources :dashboard, only: :index

  namespace :api do
    namespace :v1 do
      get 'calulate_distance', to: 'calculate_distance#distance'
    end
  end

  get 'reports/technical_payment', as: 'technical_payment'
  get 'reports/technical_clearance', as: 'technical_clearance'
  get 'reports/payment_per_vehicle', as: 'payment_per_vehicle'
  get 'reports/vehicle_liquidation', as: 'vehicle_liquidation'
  get 'reports/transaction_report', as: 'transaction_report'
  get 'reports/service_report', as: 'service_report'

end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  acts_as_paranoid
  belongs_to :enterprise
  has_many :transactions
  has_many :documents, as: :documentable, dependent: :destroy

  validates :placa, presence: true
  validates :placa, uniqueness: {scope: :enterprise_id, case_sensitive: false }
  validates :licencia, presence: true
  validates :clase, presence: true
  validates :marca, presence: true
  validates :tipo, presence: true
  validates :linea, presence: true

  has_many :pictures, as: :imageable, dependent: :destroy

  accepts_nested_attributes_for :pictures,
                                reject_if: lambda {
                                    |a| a[:image].blank? && a[:attachments].blank?
                                }, allow_destroy: true

  before_save :to_upper

  scope :is_active, -> { where(active: true) }
end

app/controllers/transactions/vehicles_controller.rb
class Transactions::VehiclesController < EnterprisesController
  def new
    @transaction = @enterprise.transactions.new(vehicle_attributes: {})
  end
end

app/controllers/vehicles/base_controller.rb
module Vehicles
  class BaseController < EnterprisesController
    before_action :load_vehicle

    private

    def load_vehicle
      @vehicle = @enterprise.vehicles.find(vehicle_id)
    end

    def vehicle_id
      params.require(:vehicle_id)
    end
  end
end

app/controllers/vehicles/documents_controller.rb
module Vehicles
  class DocumentsController < BaseController
    before_action :set_document, only: [:show, :edit, :update, :destroy]

    def index
      @q = @vehicle.documents.ransack(params[:q])
      @pagy, @documents = pagy(@q.result.includes(:document_type))
    end

    def new
      @document = @vehicle.documents.new
      @document.pictures.build
    end

    def create
      @document = @vehicle.documents.new(document_params)
      if @document.save
        redirect_to edit_vehicle_document_path(@vehicle, @document), notice: 'Document was successfully created.'
      else
        render :new
      end
    end

    def edit
      @document.pictures.build
    end

    def update
      if @document.update(document_params)
        redirect_to edit_vehicle_document_path(@vehicle, @document), notice: 'Document was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @document.destroy
      redirect_to vehicle_documents_path, notice: 'Document was deleted'
    end


    def show
      respond_to do |format|
        format.pdf do
          render pdf: "Documentos #{@vehicle.placa}",
                 title: "PDF Documentos #{@vehicle.placa}",
                 layout: 'pdf'
        end
      end
    end

    private

    def set_document
      @document = @vehicle.documents.find(params[:id])
    end

    def document_params
      params.require(:document).permit(:document_type_id, :renewable, :due_date,
                                       pictures_attributes: [:id, :image, :image_cache, :_destroy, attachments:[]]
      )
    end
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < EnterprisesController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @q = @enterprise.vehicles.ransack(params[:q])
    @pagy, @vehicles = pagy( @q.result, items: params[:per_page] == 'all' ? @q.result.count : 10 )
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "vehicle",
               template: "vehicles/show.html.slim",
               title: 'PDF Vehiculo',
               layout: 'pdf'
      end
    end
  end

  # GET /vehicles/new
  def new
    @vehicle = @enterprise.vehicles.new
    @vehicle.pictures.build
  end

  # GET /vehicles/1/edit
  def edit
    @vehicle.pictures.build
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = @enterprise.vehicles.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to edit_vehicle_path(@vehicle), notice: 'El vehiculo ha sido creado satisfactoriamente.' }
        format.json { render :edit, status: :created, location: @vehicle }
        format.js
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to edit_vehicle_path(@vehicle), notice: 'El vehiculo ha sido actualizado satisfactoriamente.' }
        format.json { render :edit, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'El vehiculo ha sido destruido satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = @enterprise.vehicles.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vehicle_params
      params.require(:vehicle).permit( :placa, :licencia, :clase, :marca, :tipo, :linea, :servicio, :combustible,
                                       :color, :modelo, :motor, :chasis, :serie, :fecha_de_compra, :contrato, :n_soat,
                                       :vencimiento_soat, :n_rtm, :vencimiento_rtm, :km_cambio_aceite, :active,
                                       :km_proximocambio, :next_oil_change_date, pictures_attributes: [ :id, :image, :image_cache, :_destroy, attachments: []])
    end
end

app/helpers/vehicles/document_helper.rb
module Vehicles::DocumentHelper
  def expired_date(document)
    if document.due_date.to_s.blank?
      expired=6
    else
      expired = ((Date.parse document.due_date.to_s) - (Date.parse Time.now.to_s)).to_i
    end

    if expired <= 0 && !document.renewable
      @expired = "<div class='alert alert-danger' role='alert'>
                    Tiene Documentos vencidos!
                  </div>"
    else
      @expired= ''
    end
  end

  def expired
    @expired
  end

end

app/helpers/vehicles_helper.rb
module VehiclesHelper

  def days_soat(vehicle)
    unless vehicle.vencimiento_soat.blank?
      ((Date.parse vehicle.vencimiento_soat.to_s) - (Date.parse Time.now.to_s)).to_i
    else
      6
    end
  end

  def days_rtm (vehicle)
    unless vehicle.vencimiento_rtm.blank?
      ((Date.parse vehicle.vencimiento_rtm.to_s) - (Date.parse Time.now.to_s)).to_i
    else
      6
    end
  end

  def days_next_oil_change_date(vehicle)
    unless vehicle.next_oil_change_date.blank?
      ((Date.parse vehicle.next_oil_change_date.to_s) - (Date.parse Time.now.to_s)).to_i
    else
      6
    end
  end

  def text_warning_soat(vehicle)
    "text-warning" if days_soat(vehicle) >= 1 && days_soat(vehicle) <= 5
  end

  def text_warning_rtm(vehicle)
    "text-warning" if days_rtm(vehicle) >= 1 && days_rtm(vehicle) <= 5
  end

  def tr_warning_o_danger(vehicle)
    if days_soat_rtm_zero(vehicle)
      "table-danger"
    elsif  days_soat_five(vehicle) || days_rtm_five(vehicle)
      return "table-warning"
    else
      ""
    end
  end

  def days_soat_zero(vehicle)
    days_soat(vehicle) <= 0
  end

  def days_rtm_zero(vehicle)
    days_rtm(vehicle) <= 0
  end

  def days_next_oil_change_date_zero(vehicle)
    days_next_oil_change_date(vehicle) <= 0
  end

  def days_soat_rtm_zero(vehicle)
    days_soat_zero(vehicle) || days_rtm_zero(vehicle)
  end

  def days_soat_five(vehicle)
    (days_soat(vehicle) >= 1 && days_soat(vehicle) <= 5)
  end

  def days_next_oil_change_date_five(vehicle)
    days_next_oil_change_date(vehicle) >= 1 && days_next_oil_change_date(vehicle) <=5
  end

  def days_rtm_five(vehicle)
    (days_rtm(vehicle) >= 1 && days_rtm(vehicle) <= 5)
  end

end

app/views/vehicles/_form.html.slim
= form_with(model: vehicle, local: true) do |form|

  = render 'vehicles/tabs', page: 'general'
  = alert_error(vehicle)

  .tab-content#nav-tabContent

    .tab-pane.fade.show.active#nav-General role="tabpanel" aria-labelledby="nav-General-tab"

      =render 'vehicles/form_fields', f: form

    - unless @vehicle.id.blank?
      .tab-pane.fade#nav-detalle role="tabpanel" aria-labelledby="nav-detalle-tab"
        .field
          = form.label :servicio
          = form.text_field :servicio, class: 'form-control'

        .field
          = form.label :combustible
          = form.text_field :combustible, class: 'form-control'

        .field
          = form.label :color
          = form.text_field :color, class: 'form-control'

        .field
          = form.label :modelo
          = form.text_field :modelo, class: 'form-control'

        .field
          = form.label :motor
          = form.text_field :motor, class: 'form-control'

        .field
          = form.label :chasis
          = form.text_field :chasis, class: 'form-control'

        .field
          = form.label :serie
          = form.text_field :serie, class: 'form-control'

        .field
          = form.label :fecha_de_compra
          = form.date_field :fecha_de_compra, class: 'form-control'

        .field
          = form.label :contrato
          = form.text_field :contrato, class: 'form-control'

      .tab-pane.fade#nav-fechas role="tabpanel" aria-labelledby="nav-fechas-tab"

        .field
          = form.label :n_soat
          = form.text_field :n_soat, class: 'form-control'

        .field
          = form.label :vencimiento_soat
          = form.date_field :vencimiento_soat, class: 'form-control'

        .field
          = form.label :n_rtm
          = form.text_field :n_rtm, class: 'form-control'

        .field
          = form.label :vencimiento_rtm
          = form.date_field :vencimiento_rtm, class: 'form-control'

        .field
          = form.label :km_cambio_aceite
          = form.text_field :km_cambio_aceite, class: 'form-control'

        .field
          = form.label :km_proximocambio
          = form.text_field :km_proximocambio, class: 'form-control'

        .field
          = form.label :next_oil_change_date, "Fecha de próximo cambio de aceite"
          = form.date_field :next_oil_change_date, class: 'form-control'

      .tab-pane.fade#nav-imagenes role="tabpanel" aria-labelledby="nav-imagenes-tab"

        = form.fields_for :pictures do |p|

          - if p.object.attachments?
            - p.object.attachments.each do |attachment|
              .field
                = p.hidden_field :image_cache, class: 'form-control'
                = p.label :attachments, "Imagen guardada"
                = p.file_field :attachments, multiple: true, class: 'form-control'
                = image_tag attachment.thumb.url, alt: 'Image'
            div
              = label_tag :_destroy do
                | Remover imagenenes
                = p.check_box :_destroy

          - else
            .field
              = p.hidden_field :image_cache, class: 'form-control'
              = p.label :attachments, "Nuevas imagenes"
              = p.file_field :attachments, multiple: true, class: 'form-control'

  .actions
    = form.submit 'Actualizar', class: 'btn btn-primary'

app/views/vehicles/_form_fields.html.slim
.field.form-check.form-check-inline
  = f.label :active
  .input-group-prepend
    .input-group-text
      = f.check_box :active
.field
  = f.label :placa
  = f.text_field :placa, class: 'form-control', id:'campo'

.field
  = f.label :licencia
  = f.text_field :licencia, class: 'form-control', id:'campo'

.field
  = f.label :clase
  = f.text_field :clase, class: 'form-control', id:'campo'

.field
  = f.label :marca
  = f.text_field :marca, class: 'form-control', id:'campo'

.field
  = f.label :tipo
  = f.text_field :tipo, class: 'form-control', id:'campo'

.field
  = f.label :linea
  = f.text_field :linea, class: 'form-control', id:'campo'

app/views/vehicles/_tabs.html.slim
nav
  .nav.nav-tabs#nav-tab role="tablist"
    a class="nav-item nav-link #{page == 'general' ? 'active' : ''}" href="#{edit_vehicle_path(@vehicle) unless @vehicle.id.nil?}" role="tab" aria-controls="nav-General" aria-selected="true"
      | General
    - unless @vehicle.id.blank?
      a.nav-item.nav-link#nav-detalle-tab data-toggle="#{page == 'general' ? 'pill' : ''}" href="#nav-detalle" role="tab" aria-controls="nav-detalle" aria-selected="false" Detalle
      a.nav-item.nav-link#nav-fechas-tab data-toggle="pill" href="#nav-fechas" role="tab" aria-controls="nav-fechas" aria-selected="false" Fechas
      a.nav-item.nav-link#nav-imagenes-tab data-toggle="pill" href="#nav-imagenes" role="tab" aria-controls="nav-imagenes" aria-selected="false" Imagenes
      a class="nav-item nav-link #{page == 'document' ? 'active' : ''}" role="tab" aria-controls="nav-documentos" aria-selected="true" href = "#{vehicle_documents_path(@vehicle)}"
        | Documentos

app/views/vehicles/create.js.erb
$(".alert").alert('close');
if (<%= @vehicle.valid? %> == true) {

    var $vehicles = $("#vehicles");

    $.getJSON('/vehicles.json?per_page=all', function (data) {
        $vehicles.empty();
        $vehicles.append($('<option>'));

        $.each(data, function (i, val) {
            $vehicles.append($('<option>', {
                value: val.id,
                text: val.placa,
                selected: val.id == parseInt("<%= @vehicle.id %>")
            }));

        });
        $('[id=campo]').each(function () {
            $(this).val('');
        });

        $('#new_vehicle_modal').modal('toggle');
    });
} else {
    <% @vehicle.errors.each do |i, v| %>
    $(".modal-body").prepend("<div class='alert alert-danger' tabindex='-2' role='alert' id='error'> <%= i  %>  <%= v  %> "+
        "<button type='button' class='close' data-dismiss='alert' aria-label='Close'>" +
        "<span aria-hidden='true'>&times;</span>" +"</button>"+ "</div>");
      console.log("<%= i %>");
      console.log("<%= v %>");
    <% end %>
}

app/views/vehicles/edit.html.slim
- content_for :breadcrumb do
  = render 'components/breadcrumb',
          title: 'Vehiculos',
          links: [['Vehiculos', vehicles_path],
                  [@vehicle.placa, '']]

- if days_soat_zero(@vehicle) && days_rtm_zero(@vehicle)

  .alert.alert-danger role="alert"
    | Las fechas de SOAT y RTM están vencidas

- elsif days_soat_zero(@vehicle)

  .alert.alert-danger role="alert"
    | La fecha de SOAT está vencida

- elsif days_rtm_zero(@vehicle)

  .alert.alert-danger role="alert"
    | La fecha de RTM está vencida


- if days_soat_five(@vehicle) && days_rtm_five(@vehicle)

  .alert.alert-warning role="alert"
    | Las fechas de SOAT y RTM están proximas a vencer

- elsif days_soat_five(@vehicle)

  .alert.alert-warning role="alert"
    | La fecha de SOAT está proxima a vencer

- elsif days_rtm_five(@vehicle)

  .alert.alert-warning role="alert"
    | La fecha de RTM está proxima a vencer

-if days_next_oil_change_date_zero(@vehicle)
  .alert.alert-danger role="alert"
    | La fecha de próximo cambio de aceite está vencida

- elsif days_next_oil_change_date_five(@vehicle)
  .alert.alert-warning role="alert"
    | La fecha de próximo cambio de aceite está proxima a vencer

= link_to 'Crear PDF', vehicle_path(@vehicle, :format => :pdf), class: 'btn btn-primary'
= render 'form', vehicle: @vehicle

app/views/vehicles/index.html.slim
- content_for :breadcrumb do
  = render 'components/breadcrumb',
          title: 'Vehiculos',
          links: [['Vehiculos', '']]

= render "components/search", url: vehicles_path, field_search: :placa_or_marca_or_n_soat_or_km_cambio_aceite_cont
table.table
  thead
    tr
      th Placa
      th Marca
      th Número de SOAT
      th Vencimiento de SOAT
      th Número de RTM
      th Vencimiento RTM
      th Km de cambio de aceite
      th Km de proximo cambio
      th colspan="3"

  tbody
    - @vehicles.each do |vehicle|

      tr class= tr_warning_o_danger(vehicle)

        td = vehicle.placa
        td = vehicle.marca
        td = vehicle.n_soat
        td class= text_warning_soat(vehicle)
          = vehicle.vencimiento_soat
        td = vehicle.n_rtm
        td class= text_warning_rtm(vehicle)
          = vehicle.vencimiento_rtm
        td = vehicle.km_cambio_aceite
        td = vehicle.km_proximocambio
        td = link_to 'Editar', edit_vehicle_path(vehicle), class: 'btn btn-primary'
        td = link_to 'Destruir', vehicle, method: :delete, data: {confirm: 'Está seguro'}, class: 'btn btn-danger'
        td = link_to 'Crear PDF', vehicle_path(vehicle, :format => :pdf), class: 'btn btn-primary'
= pagy_bootstrap_nav(@pagy).html_safe
= pagy_bootstrap_nav_js(@pagy).html_safe

br
= link_to 'Nuevo Vehiculo', new_vehicle_path, class: 'btn btn-primary'

app/views/vehicles/new.html.slim
- content_for :breadcrumb do
  = render 'components/breadcrumb',
          title: 'Vehiculos',
          links: [['Vehiculos', vehicles_path],
                  ['Nuevo', '']]

= render 'form', vehicle: @vehicle

app/views/vehicles/show.html.slim
p
  | Placa:
  strong<> = @vehicle.placa
hr

p
  | Licencia:
  strong<> = @vehicle.licencia

p
  | Clase:
  strong<> = @vehicle.clase

p
  | Marca:
  strong<> = @vehicle.marca

p
  | Tipo:
  strong<> = @vehicle.tipo

p
  | Linea:
  strong<> = @vehicle.linea

p
  | Servicio:
  strong<> = @vehicle.servicio

p
  | Combustible:
  strong<> = @vehicle.combustible

p
  | Color:
  strong<> = @vehicle.color

p
  | Modelo:
  strong<> = @vehicle.modelo

p
  | Motor:
  strong<> = @vehicle.motor

p
  | Chasis:
  strong<> = @vehicle.chasis

p
  | Serie:
  strong<> = @vehicle.serie

p
  | Fecha de compra:
  strong<> = @vehicle.fecha_de_compra


p
  | Contrato:
  strong<> = @vehicle.contrato

p
  | Numero de SOAT:
  strong<> = @vehicle.n_soat

p
  | Vencimiento de soat:
  strong<> = @vehicle.vencimiento_soat

p
  | Número de RTM:
  strong<> = @vehicle.n_rtm

p
  | Vencimiento de RTM:
  strong<> = @vehicle.vencimiento_rtm

p
  | Km de cambio de aceite:
  strong<> = @vehicle.km_cambio_aceite

p
  | Km de proximo cambio:
  strong<> = @vehicle.km_proximocambio
p
  - @vehicle.pictures.each do |p|
    - p.attachments.each do |a|
      =image_tag embed_remote_image("#{Rails.root}/public#{a.url}",'image/') if a.url