config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :accounts
  resources :services
  resources :document_types
  resources :manage_users
  resources :transactions
  resources :enterprise_aux do
    scope module: :enterprise_aux do
      resources :documents
    end
  end

  resources :vehicles do
    scope module: :vehicles do
      resources :documents
    end
  end

  resources :technicals do
    scope module: :technicals do
      resources :documents
      resources :bonding_dates
    end
  end

  resources :clients do
    scope module: :clients do
      resources :documents
      resources :list_prices
    end
  end

  get '/transactions/close/:id', to: 'transactions#close', as: 'transaction_close'
  get '/transactions/open/:id', to: 'transactions#open', as: 'transaction_open'
  get '/transactions/deliver/:id', to: 'transactions#deliver', as: 'transaction_deliver'
  get '/transactions/check_in/:id', to: 'transactions#check_in', as: 'transaction_check_in'

  namespace :transactions do
    resources :clients, only: :new
    resources :vehicles, only: :new
    resources :technicals, only: :new
    resources :accounts, only: :new
  end

  devise_for :users
  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end
  root to: redirect('/users/sign_in')
  resources :dashboard, only: :index

  namespace :api do
    namespace :v1 do
      get 'calulate_distance', to: 'calculate_distance#distance'
    end
  end

  get 'reports/technical_payment', as: 'technical_payment'
  get 'reports/technical_clearance', as: 'technical_clearance'
  get 'reports/payment_per_vehicle', as: 'payment_per_vehicle'
  get 'reports/vehicle_liquidation', as: 'vehicle_liquidation'
  get 'reports/transaction_report', as: 'transaction_report'
  get 'reports/service_report', as: 'service_report'

end

app/controllers/transactions/accounts_controller.rb
class Transactions::AccountsController < EnterprisesController
  def new
    @transaction = @enterprise.transactions.new(account_attributes: {})
  end
end

app/controllers/transactions/clients_controller.rb
class Transactions::ClientsController < EnterprisesController
  def new
    @transaction = @enterprise.transactions.new(client_attributes: {})
  end
end

app/controllers/transactions/technicals_controller.rb
class Transactions::TechnicalsController < EnterprisesController
  def new
    @transaction = @enterprise.transactions.new(technical_attributes: {})
  end
end

app/controllers/transactions/vehicles_controller.rb
class Transactions::VehiclesController < EnterprisesController
  def new
    @transaction = @enterprise.transactions.new(vehicle_attributes: {})
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < EnterprisesController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy, :open, :close, :deliver, :check_in]

  def index
    @status = params[:status]
    search_params = params[:q].nil? ? { } : params[:q].except(:status)

    case @status
    when 'open'
      @q = @enterprise.transactions.s_opened.ransack(search_params)
      @pagy, @transactions = pagy(@q.result)
    when 'delivered'
      @q = @enterprise.transactions.s_delivered.ransack(search_params)
      @pagy, @transactions = pagy(@q.result)
    when 'closed'
      @q = @enterprise.transactions.s_closed.ransack(search_params)
      @pagy, @transactions = pagy(@q.result)
    when 'invoiced'
      @q = @enterprise.transactions.s_invoiced.ransack(search_params)
      @pagy, @transactions = pagy(@q.result)
    else
      @q = @enterprise.transactions.ransack(search_params)
      @pagy, @transactions = pagy(@q.result)
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json
      format.pdf do
        render pdf: "Transaction",
               template: "transactions/show.html.slim",
               title: 'PDF  Transaction',
               layout: 'pdf'
      end
    end
  end

  def new
    @transaction = @enterprise.transactions.new(fecha: Time.now.strftime("%Y-%m-%d %H:%M %z"),
                                                service_number: @enterprise.service_number,
                                                total_km: 0,
                                                km_zona_normal: 0,
                                                km_zona_roja: 0)
    @transaction.observations.build(user_id: current_user.id)
    @transaction.pictures.build
  end

  def edit
    @transaction.observations.build(user_id: current_user.id)
    @transaction.pictures.build
  end

  def create
    @transaction = @enterprise.transactions.new(transaction_params)
    respond_to do |format|
      if @transaction.save
        format.html { redirect_to edit_transaction_path(@transaction), notice: 'La Transacción ha sido creada satisfactoriamente.' }
        format.json { render :edit, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to edit_transaction_path(@transaction), notice: 'La Transacción ha sido actualizada satisfactoriamente.' }
        format.json { render :edit, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @transaction.destroy
    redirect_to transactions_path, notice: 'La Transacción ha sido destruida satisfactoriamente.'
  end

  def close
    respond_to do |format|
      if @transaction.close
        format.html { redirect_to edit_transaction_path(@transaction), notice: 'La Transacción ha sido cerrada satisfactoriamente.' }
        format.json { render :edit, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def open
    respond_to do |format|
      if @transaction.open
        format.html { redirect_to edit_transaction_path(@transaction), notice: 'La Transacción ha sido abierta satisfactoriamente.' }
        format.json { render :edit, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def deliver
    respond_to do |format|
      if @transaction.deliver
        format.html { redirect_to edit_transaction_path(@transaction), notice: 'La Transacción ha sido enviada satisfactoriamente.' }
        format.json { render :edit, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def check_in
    respond_to do |format|
      if @transaction.check_in
        format.html { redirect_to edit_transaction_path(@transaction), notice: 'La Transacción ha sido faturada satisfactoriamente.' }
        format.json { render :edit, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_transaction
    @transaction = @enterprise.transactions.find(params[:id])
  end

  def transaction_params
    unless params[:transaction][:technical].blank?

      params[:transaction][:technical_attributes] = {id: params[:transaction][:technical][:id],
                                                     telefono1: params[:transaction][:technical][:telefono1],
                                                     telefono2: params[:transaction][:technical][:telefono2]}
    end

    params.require(:transaction).permit(:status, :fecha, :orden_Trabajo, :service_number, :remision, :factura, :hora_llegada,
                                        :response_time, :hora_final, :client_id, :account_id, :expediente, :placa, :tarea, :origen,
                                        :lat, :lng, :destino, :latb, :lngb, :asegurado, :direccion, :telefono,
                                        :technical_id, :vehicle_id, :total_km, :km_zona_normal, :total_normal_zone,
                                        :km_zona_roja, :total_red_zone, :banderazo,
                                        :valor_km_zona_n, :valor_km_zona_r, :horas_de_espera, :waiting_hours_value,
                                        :total_waiting_hours, :rango_nocturno, :recargo_festivo, :valor_servicio,
                                        :priced, :operador, :celula_costo, :fecha_de_cierre,
                                        :descuento, :pago_total, :porcentaje_tecnico, :pago_tecnico, :combustible,
                                        :peajes, :gasto_viaje, :gastos, :ganancias, :service_id,
                                        observations_attributes: [:id, :user_id, :description, :_destroy],
                                        pictures_attributes: [:id, :image, :image_cache, :_destroy, attachments: []],
                                        client_attributes: [:nombre, :tipo_identificacion, :identificacion, :razon_social, :regimen, :actividad_comercial,
                                                            :direccion, :ciudad, :telefono, :email, :enterprise_id, account_ids: []],
                                        vehicle_attributes: [:enterprise_id, :placa, :licencia, :clase, :marca, :tipo, :linea, :servicio],
                                        technical_attributes: [:id, :enterprise_id, :nombre, :cedula, :cargo, :direccion, :telefono1,
                                                               :telefono2, :fecha_nacimiento, :n_licencia,
                                                               :categoria, :eps, :arl],
                                        account_attributes: [:name, :enterprise_id, :client_ids])


  end
end

app/helpers/transactions/accounts_helper.rb
module Transactions::AccountsHelper
end

app/helpers/transactions/clients_helper.rb
module Transactions::ClientsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/edit.html.slim
- content_for :breadcrumb do
  = render 'components/breadcrumb',
          title: 'Transacción',
          links: [['Transacción', transactions_path],
                  ['Editar', '']]

= link_to 'Crear PDF', transaction_path(@transaction, :format => :pdf), class: 'btn btn-primary'
| |
.btn_clip_board.btn.btn-primary
  | Copiar

= render 'form', transaction: @transaction

div id='data_transaction' data-transaction="#{@transaction.to_json(include: [
                                                                             :enterprise,
                                                                             :service_including_deleted,
                                                                             :technical_including_deleted,
                                                                             :account_including_deleted,
                                                                             :vehicle_including_deleted
                                                                             ])}"

app/views/transactions/index.html.slim
- content_for :breadcrumb do
  = render 'components/breadcrumb',
          title: 'Transacción',
          links: [ ['Transacción', ''] ]

= render "components/search",
        url: transactions_path,
        field_search: :status_or_expediente_or_orden_Trabajo_or_remision_or_factura_or_technical_nombre_or_technical_cedula_or_client_nombre_or_client_identificacion_or_client_telefono_or_client_ciudad_or_vehicle_placa_cont

table.table
  thead
    tr
      th Estado
      th Fecha y hora
      th Orden_Trabajo
      th Remision
      th Expediente
      th factura
      th Asegurado
      th Cliente

      th colspan="3"
  tbody
    - @transactions.each do |transaction|

      tr
        td = transaction.status
        td = transaction.fecha
        td = transaction.orden_Trabajo
        td = transaction.remision
        td = transaction.expediente
        td = transaction.factura
        td = transaction.asegurado
        td = transaction.client_including_deleted.nombre
        td = link_to 'Editar', edit_transaction_path(transaction), class: 'btn btn-primary'
        td = link_to 'Destruir', transaction, method: :delete, data: {confirm: 'Está seguro?'}, class: 'btn btn-danger'
        td = link_to 'Crear PDF', transaction_path(transaction, :format => :pdf), class: 'btn btn-primary'

= pagy_bootstrap_nav(@pagy).html_safe
= pagy_bootstrap_nav_js(@pagy).html_safe

br
= link_to 'Nueva Transacción', new_transaction_path, class: 'btn btn-primary'

app/views/transactions/new.html.slim
- content_for :breadcrumb do
  = render 'components/breadcrumb',
          title: 'Transacción',
          links: [ ['Transacción', transactions_path],
                   ['Nueva', '']]

= render 'form', transaction: @transaction

app/views/transactions/show.html.slim
p
  strong Fecha y hora:
  = @transaction.fecha
p
  strong Expediente:
  = @transaction.expediente
p
  strong Remisióm:
  = @transaction.remision

p
  strong Cliente:
  = @transaction.client_including_deleted.nombre

p
  strong Cuenta:
  = @transaction.account_including_deleted.name

p
  strong Placa de servicio:
  = @transaction.placa

p
  strong Tarea:
  = @transaction.tarea

p
  strong Origen:
  = @transaction.origen

p
  strong Destino:
  = @transaction.destino

p
  strong Asegurado:
  = @transaction.asegurado

p
  strong Telefono:
  = @transaction.telefono

p
  strong Dirección asegurado:
  = @transaction.direccion

p
  strong Placa Grua:
  = @transaction.vehicle_including_deleted.placa

p
  - @transaction.pictures.each do |p|
    - p.attachments.each do |a|
      =image_tag embed_remote_image("#{Rails.root}/public#{a.url}",'image/') if a.url